version: "3"

services:

  dremio:
    container_name: dremio 
    user: root
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    volumes:
      - ./core-site.xml:/opt/dremio/conf/core-site.xml
      - ./dremio.conf:/opt/dremio/conf/dremio.conf
      # - ./dremio-env:/opt/dremio/conf/dremio-env
      # - ./dremio_data:/opt/dremio/data
    ports:
      - "9047:9047"   # UI (HTTP)
      - "31010:31010" # ODBC/JDBC clients
      - "2181:2181"   # ZooKeeper
      - "45678:45678" # Inter-node communication
    networks:
      - minionetwork

networks:
  minionetwork:
    external: true
